# Generated by Django 2.2.3 on 2019-07-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('o', models.DecimalField(decimal_places=1, max_digits=3)),
                ('h', models.DecimalField(decimal_places=1, max_digits=3)),
                ('l', models.DecimalField(decimal_places=1, max_digits=3)),
                ('c', models.DecimalField(decimal_places=1, max_digits=3)),
                ('volumn', models.BigIntegerField()),
                ('dividends', models.DecimalField(decimal_places=1, max_digits=3)),
                ('splits', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'db_table': 'AAPL',
                'managed': True,
            },
        ),
    ]
