# Generated by Django 2.2.3 on 2019-07-31 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldata',
            options={'managed': True, 'ordering': ['-Date']},
        ),
        migrations.RenameField(
            model_name='historicaldata',
            old_name='c',
            new_name='Close',
        ),
        migrations.RenameField(
            model_name='historicaldata',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='historicaldata',
            old_name='dividends',
            new_name='Dividends',
        ),
        migrations.RenameField(
            model_name='historicaldata',
            old_name='h',
            new_name='High',
        ),
        migrations.RenameField(
            model_name='historicaldata',
            old_name='l',
            new_name='Low',
        ),
        migrations.RenameField(
            model_name='historicaldata',
            old_name='o',
            new_name='Open',
        ),
        migrations.RenameField(
            model_name='historicaldata',
            old_name='splits',
            new_name='Splits',
        ),
        migrations.RenameField(
            model_name='historicaldata',
            old_name='volumn',
            new_name='Volume',
        ),
    ]
