# Generated by Django 2.2.3 on 2019-08-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_auto_20190731_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldata',
            options={'managed': True, 'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='historicaldata',
            old_name='Date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='Close',
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='Dividends',
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='High',
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='Low',
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='Open',
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='Splits',
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='Volume',
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='close',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='dividends',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='high',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='low',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='open',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='splits',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='volume',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='historicaldata',
            table='',
        ),
    ]
