# Generated by Django 2.2.3 on 2019-08-01 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_auto_20190801_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldata',
            options={'ordering': ['-date']},
        ),
    ]
